### ISSUE TITLE
Lambda function invoked before credentials retrieved/written to disk

### ISSUE THREAD

**Issue by armandAkop** [hashicorp/vault-lambda-extension#31] opened 2021-04-19 18:01 UTC
Lambda Runtime: Node 14x

Hi, I've noticed some errors when trying to read my vault secret with path `/tmp/vault/secret.json`. This seems to only happen when the lambda function hasn't been invoked in a while (30+ minutes). Once the lambda fails, the coordinating step function retries and it is successful the second time around. Here is the initial error from the cloudwatch logs. 

Notice: "authenticating to Vault", then it seems to jump straight to the code which tries to read the secret.

```

  | 2021-04-19T10:20:19.365-07:00 | [vault-lambda-extension] 2021/04/19 17:20:19 Initialising
-- | -- | --
  | 2021-04-19T10:20:19.365-07:00 | [vault-lambda-extension] 2021/04/19 17:20:19 authenticating to Vault
  | 2021-04-19T10:20:20.134-07:00 | 2021-04-19T17:20:20.133Z undefined ERROR Uncaught Exception {"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module '/tmp/vault/secret.json'\nRequire stack:\n- /var/task/services/secretReader.js\n
  | 2021-04-19T10:20:20.147-07:00 | EXTENSION Name: vault-lambda-extension State: Registered Events: [INVOKE,SHUTDOWN]
```

Then on the following **successful** invocation...

```
  | 2021-04-19T10:20:20.462-07:00 | [vault-lambda-extension] 2021/04/19 17:20:20 Initialising
-- | -- | --
  | 2021-04-19T10:20:20.462-07:00 | [vault-lambda-extension] 2021/04/19 17:20:20 authenticating to Vault
  | 2021-04-19T10:20:21.198-07:00 | [vault-lambda-extension] 2021/04/19 17:20:21 Initialised
  | 2021-04-19T10:20:21.198-07:00 | [vault-lambda-extension] 2021/04/19 17:20:21 Waiting for event...
  | 2021-04-19T10:20:21.198-07:00 | [vault-lambda-extension] 2021/04/19 17:20:21 Starting HTTP server
  | 2021-04-19T10:20:23.056-07:00 | EXTENSION Name: vault-lambda-extension State: Ready Events: [INVOKE,SHUTDOWN]
  | 2021-04-19T10:20:23.057-07:00 | [vault-lambda-extension] 2021/04/19 17:20:23 Received event
  | 2021-04-19T10:20:23.057-07:00 | [vault-lambda-extension] 2021/04/19 17:20:23 Waiting for event...
  | 2021-04-19T10:20:23.096-07:00 | 2021-04-19T17:20:23.085Z 470e64df-82b9-438b-9290-142b3f63edfb INFO Begin Lambda
```

Here is what my lambda looks like

```node
const secretReader = require('./secretReader');
const secret = secretReader.read(); // This is what calls require('/tmp/vault/secret.json')

exports.handler = async (event, context) => {
  console.log('Begin Lambda');
};
```

Why is this happening? Is it because the .js is loaded and the outer scope is executed before vault can finish loading the secret and writing to disk?

**Comment by tomhjp** [comment] 2021-04-22 12:14
Thanks for raising, this looks odd, I agree it looks like the .js is running before the extension has finished initialising but that shouldn't be possible. The Lambda runtime should wait until the extension has called the `/event/next` endpoint for the first time before allowing the Lambda to start, because that's the signal that the extension initialisation phase is complete.

Your comment about it happening only after 30+ minutes of inactivity is interesting, and suggests it's only occurring in fresh execution environments. You can force Lambda to create a new execution environment by changing/adding any environment variable. Are you able to reproduce reliably after changing an environment variable?

Lastly, please could you share some more of the configuration for your Lambda function to help me get a repro? Especially the environment variables (redacted values if necessary) and version of the extension in use.

**Comment by armandAkop** [comment] 2021-04-22 16:41
I will work on reproducing this today and get you more information. In the meantime, I was reading the [extension documentation](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-context.html#runtimes-lifecycle-ib) and noticed this snippet about the lifecycle:

> Init: In this phase, Lambda creates or unfreezes an execution environment with the configured resources, downloads the code for the function and all layers, initializes any extensions, initializes the runtime, **and then runs the function’s initialization code (the code outside the main handler)**

> In the Init phase, Lambda performs three tasks:
> - Start all extensions (Extension init)
> - Bootstrap the runtime (Runtime init)
> - Run the function's static code (Function init)
> 

Did a little more Googling and found [this](https://lumigo.io/blog/aws-lambda-extensions-what-are-they-and-why-do-they-matter/)
> Extension inits are started in parallel.

If my understanding is correct, this seems like it would be expected behavior since my `secretReader.read()` is called outside of the function handler.

I will keep you updated when I reproduce.

**Comment by tomhjp** [comment] 2021-04-22 16:58
Interesting, I did know extensions initialise in parallel but my understanding was that because the `require` is part of the Lambda code, that shouldn't be part of the extensions init phase. I would expect `require` to be the first thing that runs _after_ the extension/runtime init phases. Do `require`s count as some sort of internal extension or something? I'm not too familiar with the JavaScript runtime for Lambda so I may be missing something there.

**Comment by JinlianWang** [comment] 2022-03-01 15:43
@armandAkop @kevingunn-wk @tomhjp there actually could be a solution for this.  Can you test and confirm that it fixes your cases? For more context, we talked to AWS and here is the explanation of the situation which were misunderstood, even by AWS its own developers/sample projects: 

> Extension init completion is triggered by /extension/event/next. However, Lambda does not wait until /extension/event/next to start the runtime init – it starts runtime init after /extension/register. Extensions can complete init anytime during sandbox initialization (the overall init phase is considered complete when the runtime and each registered extension call /next).

**Comment by tomhjp** [comment] 2022-04-01 17:41
Thanks for raising this @JinlianWang - I have verified your fix and it all looks good 👍 we should be able to reliably read secrets from static function code from the next release 🎉 e.g. for a python function this reliably works fine, printing the secret (not for prod use 😅) once per execution environment, and printing the "handler invoked" line once per function execution:

```python
print("static code invoked")
with open('/tmp/vault_secret.json', 'r') as secrets:
    secret = secrets.read()
    print(secret)

def lambda_handler(event, context):
    print("handler invoked")
```

**Comment by JinlianWang** [comment] 2022-04-01 17:58
Woohoo, thanks @tomhjp for handling it. Glad that we can close this issue 😄

**Closed** 2022-04-04 09:50 UTC
Labels: documentation
